exclude_patterns:
  - "Documentation/"
  - "application"
  - "cello/cello-clustering"
  - "cello/cello-common/src/main/java/org/cellocad/v2/results/partitioning"
  - "cello/cello-logicoptimization"
  - "cello/cello-partitioning"
  - "cello/tools"
  - "sample-input"
  - "tools-test"
  - "vinny-tools"
