branches:
  only:
    - develop
    - master
os:
  - linux
  - osx
osx_image: xcode9.3
dist: trusty
language: java
jdk:
  - oraclejdk8
services:
  - docker
addons:
  homebrew:
    packages:
      - yosys
      - graphviz
    update: true
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:saltmakrell/ppa -y; sudo apt-get update; sudo apt-get -y install graphviz yosys; sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386; fi
  - cd cello/
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true
after_success:
  - cd cello-dnacompiler/
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$DOCKER_USERNAME" != "" ] && [ "$DOCKER_PASSWORD" != "" ]; then mvn docker:build -Ddocker.showLogs=false && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && mvn docker:push -Ddocker.showLogs=false; fi
