os:
  - linux
  - osx
osx_image: xcode9.3
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  homebrew:
    packages:
      - yosys
      - graphviz
    update: true
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository ppa:saltmakrell/ppa -y; sudo apt-get update; sudo apt-get -y install graphviz yosys; sudo dpkg --add-architecture i386; sudo apt-get update; sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386; fi
  - cd cello/
